# Generated by Django 2.2.6 on 2019-10-22 03:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('password', models.CharField(max_length=256)),
                ('role', models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher')], default='student', max_length=32)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('c_time', models.DateTimeField(auto_now_add=True)),
                ('has_confirmed', models.BooleanField(default=False)),
                ('firstname', models.CharField(default='null', max_length=128)),
                ('lastname', models.CharField(default='null', max_length=128)),
                ('img', models.ImageField(blank=True, default='img/usyd_grad.jpeg', null=True, upload_to='img')),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('none', 'None')], default='male', max_length=32)),
                ('organization', models.CharField(default='null', max_length=128)),
                ('title', models.CharField(choices=[('assistant', 'Assistant'), ('associate professor', 'Associate Professor'), ('dr', 'Dr'), ('lecturer', 'Lecturer'), ('management', 'Management'), ('phd', 'Phd'), ('postdoc', 'Postdoc'), ('professor', 'Professor'), ('research assistant', 'Research Assistant'), ('researcher', 'Researcher')], default='null', max_length=32)),
                ('field', models.CharField(choices=[('agricultural science', 'Agricultural Science'), ('anthropology', 'Anthropology'), ('biology', 'Biology'), ('computer science', 'Computer Science'), ('engineering', 'Engineering'), ('mathematics', 'Mathematics'), ('physics', 'Physics'), ('social science', 'Social Science')], default='null', max_length=32)),
                ('country', models.CharField(default='null', max_length=128)),
                ('location', models.CharField(default='null', max_length=128)),
                ('statement', models.TextField(default='null', max_length=128)),
            ],
            options={
                'verbose_name': 'Account',
                'verbose_name_plural': 'Account',
                'ordering': ['-c_time'],
            },
        ),
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(blank=True)),
                ('starttime', models.TimeField(blank=True, null=True)),
                ('duration', models.CharField(choices=[('30 Minutes', '30 Minutes'), ('1 hour', '1 hour')], default='null', max_length=32)),
                ('method', models.CharField(choices=[('meeting', 'Meeting'), ('skype', 'Skype'), ('zoom', 'Zoom'), ('other method', 'Other method')], default='null', max_length=32)),
                ('location_id', models.CharField(default='null', max_length=128)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='login.User')),
            ],
        ),
        migrations.CreateModel(
            name='ConfirmString',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=256)),
                ('c_time', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='login.User')),
            ],
            options={
                'verbose_name': 'Confirmation code',
                'verbose_name_plural': 'Confirmation code',
                'ordering': ['-c_time'],
            },
        ),
    ]
