# Generated by Django 2.2.6 on 2019-10-22 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('student_id', models.CharField(max_length=256)),
                ('scientist_id', models.CharField(max_length=256)),
                ('date', models.DateField(blank=True)),
                ('starttime', models.TimeField(blank=True, null=True)),
                ('duration', models.CharField(default='null', max_length=32)),
                ('method', models.CharField(default='null', max_length=32)),
                ('location_id', models.CharField(default='null', max_length=128)),
            ],
        ),
    ]
