# Generated by Django 2.2.6 on 2019-10-22 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='confirm_id',
            field=models.CharField(default='null', max_length=128),
        ),
    ]
