# Generated by Django 2.2.6 on 2019-10-22 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_appointment_confirm_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='scientist_firstname',
            field=models.CharField(default='null', max_length=128),
        ),
        migrations.AddField(
            model_name='appointment',
            name='scientist_lastname',
            field=models.CharField(default='null', max_length=128),
        ),
    ]
