# Generated by Django 2.2.6 on 2019-10-22 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_auto_20191022_2259'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='appointer_firstname',
            field=models.CharField(default='null', max_length=128),
        ),
        migrations.AddField(
            model_name='appointment',
            name='appointer_lastname',
            field=models.CharField(default='null', max_length=128),
        ),
    ]
