# Generated by Django 2.2.6 on 2019-10-22 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_auto_20191022_2342'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='appointer_email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
