# Generated by Django 2.2.6 on 2019-10-23 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_appointment_appointer_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appointer_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
