# Generated by Django 2.2.6 on 2019-11-01 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0010_timetable_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='scientist_message_status',
            field=models.CharField(default='unread', max_length=32),
        ),
        migrations.AddField(
            model_name='appointment',
            name='student_message_status',
            field=models.CharField(default='unread', max_length=32),
        ),
    ]
